
<?php

$e = $myException;
?>
<?php while($e) : ?>
    <div class="page-header">
        <h1>
            <?= $e->message ?>
        </h1>
    </div>
    <table class="table">
        <?php foreach($e->traces as $trace): ?>
            <?php /** @var \BetterError\Trace $trace */ ?>
            <tr>
                <td>
                    <?= $trace->getMethod() ?><br />
                    <?= $trace->strippedFile() ?>
                    <span class="label label-default">
                    <?= $trace->line ?>
                    </span>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php
$e = $e->next;
endwhile;
?>